/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function validateApiKeyRust(apiKey: string): boolean
export declare function rustVersion(): string
export declare class RustGeminiClient {
  constructor(apiKey: string, modelName?: string | undefined | null, temperature?: number | undefined | null)
  chat(prompt: string): Promise<string>
  clearHistory(): Promise<void>
  getHistoryCount(): Promise<number>
}
